---
_hotel_id: RES876
_portal_id: required-but-empty
_root_path: https://qa5.ttaws.com/rt
latitude: 42.29415
longitude: -71.4864
name: Residence Inn by Marriott Boston Framingham
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: 400 Staples Drive
  street2: ''
  state: Massachusetts
  city: Framingham
  country: United States
  zip_code: '01702'
